# Generated by Django 5.1.6 on 2025-11-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_previousyearquestion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousyearquestion',
            name='paper_file',
            field=models.FileField(upload_to=''),
        ),
    ]
